### ISSUE TITLE
这里是不是没有处理登录失败的场景，为什么要把Authentication放入上下文？

### ISSUE THREAD

**Issue by pzs-pzs** [hansonwang99/Spring-Boot-In-Action#2]
https://github.com/hansonwang99/Spring-Boot-In-Action/blob/440e464250f5bd1a3ef970bf40cf480aa1493356/springbt_security_jwt/src/main/java/cn/codesheep/springbt_security_jwt/service/impl/AuthServiceImpl.java#L45

**Comment by hansonwang99** [comment]
执行用户名和密码认证啊，借助这个authentication
