### ISSUE TITLE
基于Tomcat版本造成的java.lang.IllegalStateException

### ISSUE THREAD

**Issue by DragonBaby308** [hansonwang99/Spring-Boot-In-Action#5]
部分情况会出现java.lang.IllegalStateException:Calling [asyncError()] is not valid for a request with Async state。
解决方法：排除Tomcat依赖，使用Jetty代替。

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jetty</artifactId>
        </dependency>

**Comment by DragonBaby308** [comment]
针对的项目是Spring-Boot-Admin2.0

**Comment by hansonwang99** [comment]
ths
